import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  locationPromptBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.48)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  locationPromptCard: { width: '100%', maxWidth: 420, backgroundColor: '#fff', borderRadius: 24, padding: 22, alignItems: 'center' },
  locationPromptTitle: { marginTop: 10, fontSize: 18, fontWeight: '900', color: '#064e3b', textAlign: 'center' },
  locationPromptText: { marginTop: 8, fontSize: 13, lineHeight: 21, color: '#475569', textAlign: 'center' },
  locationPromptActions: { width: '100%', flexDirection: 'row-reverse', gap: 10, marginTop: 18 },
  locationPromptAllow: { flex: 1, backgroundColor: '#059669', borderRadius: 14, padding: 13, alignItems: 'center' },
  locationPromptAllowText: { color: '#fff', fontWeight: '900' },
  locationPromptLater: { flex: 1, backgroundColor: '#f1f5f9', borderRadius: 14, padding: 13, alignItems: 'center' },
  locationPromptLaterText: { color: '#475569', fontWeight: '900' },
  container: {
    flex: 1,
    backgroundColor: '#f6f8f7',
  },
  hero: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingTop: Platform.OS === 'ios' ? 52 : 18,
    paddingBottom: 20,
    paddingHorizontal: 16,
    backgroundColor: '#064e3b',
    borderBottomWidth: 0,
    borderBottomColor: 'transparent',
  },
  topNavRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  brandAndLocation: {
    alignItems: 'flex-end',
  },
  brandTitleRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  headerLogo: {
    width: 38,
    height: 38,
    marginLeft: 7,
  },
  locationSelectorPill: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    gap: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  locationSelectorText: {
    color: '#ecfdf5',
    fontSize: 11,
    fontWeight: '800',
    maxWidth: 200,
  },
  leftActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  avatarWrap: {
    position: 'relative',
  },
  avatarImg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#fff',
  },
  avatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  avatarLetter: {
    color: '#ecfdf5',
    fontSize: 18,
    fontWeight: '900',
  },
  avatarVerifiedBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#16a34a',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  iconCircleBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.14)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    position: 'relative',
  },
  notifBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#ef4444',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  notifBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
  },
  searchBarContainer: {
    paddingHorizontal: 20,
  },
  searchBar: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 3,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: '#0f172a',
    textAlign: 'right',
  },
  micBtn: {
    padding: 6,
  },
  clearSearchBtn: {
    padding: 6,
  },
  fullSearchMiniBtn: {
    backgroundColor: '#059669',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  fullSearchMiniText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  fullSearchTriggerBtn: {
    backgroundColor: '#ecfdf5',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  fullSearchTriggerText: {
    color: '#047857',
    fontSize: 11,
    fontWeight: '800',
  },
  quickTagsRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    flexWrap: 'wrap',
  },
  quickTagPill: {
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  quickTagPillActive: {
    backgroundColor: '#ecfdf5',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#6ee7b7',
  },
  quickTagText: {
    color: '#ecfdf5',
    fontSize: 11,
    fontWeight: '700',
  },
  quickTagTextActive: {
    color: '#047857',
    fontSize: 11,
    fontWeight: '800',
  },
  // Atmosphere & Neighborhood Pulse Bar
  atmosphereBar: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: -14,
    marginBottom: 12,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    zIndex: 10,
  },
  atmoItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  atmoText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#334155',
  },
  atmoDivider: {
    width: 1,
    height: 16,
    backgroundColor: '#e2e8f0',
  },

  // Upgraded Stories Section
  storiesContainer: {
    paddingVertical: 14,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  storiesHeaderRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  storiesTitleRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  storiesSectionTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0f172a',
  },
  storiesLiveBadge: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#ecfdf5',
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#a7f3d0',
    gap: 4,
  },
  storiesLivePulseDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#10b981',
  },
  storiesLiveText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#059669',
  },
  publishStoryHeaderBtn: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 10,
    paddingVertical: 4.5,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    gap: 4,
  },
  publishStoryHeaderText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#059669',
  },
  storiesScroll: {
    paddingHorizontal: 16,
    gap: 14,
    alignItems: 'flex-start',
  },
  storyBox: {
    alignItems: 'center',
    width: 68,
  },
  storyAddRing: {
    width: 66,
    height: 66,
    borderRadius: 33,
    padding: 2.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  storyGradientRing: {
    width: 66,
    height: 66,
    borderRadius: 33,
    padding: 2.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
    position: 'relative',
  },
  storyInnerBorder: {
    width: '100%',
    height: '100%',
    borderRadius: 31,
    borderWidth: 2,
    borderColor: '#fff',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    position: 'relative',
  },
  storySelfPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#ecfdf5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  storySelfPlusBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#059669',
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  storyImg: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
  },
  storyTextPreview: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  storyTextPreviewLetter: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '900',
  },
  storyVerifiedTag: {
    position: 'absolute',
    bottom: -1,
    right: -1,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#16a34a',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  storyName: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
  },
  storyDistrictSub: {
    fontSize: 9.5,
    color: '#64748b',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 1,
  },

  // Service Pill Badges
  servicePillBadge: {
    position: 'absolute',
    top: -5,
    right: -6,
    backgroundColor: '#059669',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#fff',
    zIndex: 5,
  },
  servicePillBadgeText: {
    color: '#fff',
    fontSize: 7.5,
    fontWeight: '900',
  },
  emergencyHomeCard: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: '#fef2f2',
    borderRadius: 18,
    padding: 14,
    borderWidth: 2,
    borderColor: '#fca5a5',
  },
  emergencyHomeHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  emergencyHomeTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#dc2626',
  },
  emergencyLiveBadge: {
    backgroundColor: '#dc2626',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  emergencyLiveText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '900',
  },
  emergencyContentBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  emergencyQuestionTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#991b1b',
    textAlign: 'right',
  },
  emergencyQuestionSub: {
    fontSize: 11,
    color: '#dc2626',
    textAlign: 'right',
    marginTop: 3,
  },
  moreBannerCard: {
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 4,
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#059669',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  moreBannerGrad: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 12,
  },
  moreBannerContent: {
    flex: 1,
    alignItems: 'flex-end',
  },
  moreBannerBadge: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    marginBottom: 5,
  },
  moreBannerBadgeText: {
    color: '#fef08a',
    fontSize: 10,
    fontWeight: '900',
  },
  moreBannerTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  moreBannerSub: {
    color: '#d1fae5',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'right',
    marginTop: 2,
  },
  moreBannerBtn: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  moreBannerBtnText: {
    color: '#064e3b',
    fontSize: 12,
    fontWeight: '900',
  },
  servicesGrid: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 14,
    marginBottom: 8,
  },
  servicePill: {
    alignItems: 'center',
    width: (width - 48) / 6,
  },
  serviceIconBox: {
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  serviceLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#334155',
    textAlign: 'center',
  },
  feedSection: {
    marginTop: 12,
    paddingHorizontal: 16,
  },
  floatingTabs: {
    flexDirection: 'row-reverse',
    gap: 8,
    marginBottom: 14,
    paddingVertical: 4,
  },
  fTab: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
  },
  fTabActive: {
    backgroundColor: '#059669',
    borderColor: '#059669',
  },
  fTabActiveRed: {
    backgroundColor: '#dc2626',
    borderColor: '#dc2626',
  },
  fTabActiveGreen: {
    backgroundColor: '#16a34a',
    borderColor: '#16a34a',
  },
  fTabActiveMine: {
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
  },
  fTabText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#475569',
  },
  fTabLabelRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  fTabTextActive: {
    color: '#fff',
  },
  // Empty state & FAB
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderRadius: 20,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  emptyIconBg: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#ecfdf5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#1e293b',
    marginBottom: 6,
    textAlign: 'center',
  },
  emptySub: {
    fontSize: 13,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 16,
  },
  emptyAskBtn: {
    backgroundColor: '#059669',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 14,
  },
  emptyAskBtnText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  fabContainer: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 88 : 76,
    left: 20,
    zIndex: 99,
    borderRadius: 30,
    shadowColor: '#059669',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  fabBtn: {
    borderRadius: 30,
  },
  fabGrad: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 30,
    gap: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  fabText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '900',
  },
  locationGateOverlay: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 22,
  },
  locationGateCard: {
    width: '100%',
    maxWidth: 430,
    backgroundColor: '#fff',
    borderRadius: 28,
    padding: 24,
    alignItems: 'stretch',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.2,
    shadowRadius: 28,
    elevation: 12,
  },
  locationGateIcon: {
    alignSelf: 'center',
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#ecfdf5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  locationGateTitle: {
    color: '#0f172a',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 9,
  },
  locationGateText: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: 16,
  },
  locationGateStatus: {
    backgroundColor: '#f8fafc',
    borderRadius: 16,
    padding: 13,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 12,
  },
  locationGateStatusRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  locationGateStatusText: {
    flex: 1,
    color: '#334155',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  locationGateMessage: {
    color: '#64748b',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    marginBottom: 12,
  },
  locationGatePrimary: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: '#059669',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  locationGatePrimaryText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  locationGateRequired: {
    color: '#94a3b8',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 11,
  },

  bottomNavWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },



  skeletonCard: { backgroundColor: '#fff', borderRadius: 20, padding: 16, marginHorizontal: 16, marginBottom: 12, gap: 10 },
  skeletonLine: { height: 12, borderRadius: 6, backgroundColor: '#e2e8f0' },
  errorBanner: { marginHorizontal: 16, marginTop: 12, padding: 14, borderRadius: 16, backgroundColor: '#fef2f2', borderWidth: 1, borderColor: '#fecaca', flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  errorBannerText: { flex: 1, color: '#991b1b', fontSize: 13, fontWeight: '700', textAlign: 'right' },
  errorRetryBtn: { backgroundColor: '#dc2626', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 8 },
  errorRetryText: { color: '#fff', fontWeight: '800', fontSize: 12 },
  loadMoreBtn: { alignSelf: 'center', marginVertical: 14, paddingHorizontal: 22, paddingVertical: 11, borderRadius: 999, backgroundColor: '#ecfdf5', borderWidth: 1, borderColor: '#a7f3d0' },
  loadMoreText: { color: '#047857', fontWeight: '800', fontSize: 13 },
  heroGreeting: { color: '#a7f3d0', fontSize: 14, fontWeight: '800', textAlign: 'right', marginTop: 10, marginBottom: 2 },
});
