import { StyleSheet, Platform } from 'react-native';

export const chatStyles = StyleSheet.create({
  container: {
    flex: 1,
    minHeight: Platform.OS === 'web' ? ('100vh' as any) : undefined,
    width: '100%',
    alignSelf: 'stretch',
    backgroundColor: '#f8fafc',
  },
  inner: {
    width: '100%',
    maxWidth: 1100,
    alignSelf: 'center',
    paddingHorizontal: 16,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    width: '100%',
    backgroundColor: '#064e3b',
    paddingTop: Platform.OS === 'ios' ? 44 : 10,
    paddingBottom: 8,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  headerTop: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  headerLegacy: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 1100,
    alignSelf: 'center',
    paddingHorizontal: 14,
    paddingTop: Platform.OS === 'ios' ? 44 : 10,
    paddingBottom: 8,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  headerUser: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    flex: 1,
    marginRight: 6,
    gap: 10,
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 13,
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  headerAvatarFallback: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  headerAvatarLetter: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  headerInfo: {
    alignItems: 'flex-end',
    flex: 1,
  },
  headerNameRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  headerName: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  headerCity: {
    color: '#a7f3d0',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 1,
  },
  headerStatusPill: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.15)',
    marginLeft: 6,
  },
  headerStatusText: {
    color: '#a7f3d0',
    fontSize: 11,
    fontWeight: '800',
  },
  headerStatusRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 5,
    marginTop: 2,
    paddingRight: 48,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  statusDotOnline: {
    backgroundColor: '#34d399',
  },
  headerActions: {
    flexDirection: 'row-reverse',
  },
  headerActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },

  noticeBlocked: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#fef2f2',
    borderBottomWidth: 1,
    borderColor: '#fca5a5',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  noticeBlockedText: {
    flex: 1,
    color: '#dc2626',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
    marginRight: 6,
  },
  unblockQuickBtn: {
    backgroundColor: '#dc2626',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  unblockQuickText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  noticeMuted: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#fffbeb',
    borderBottomWidth: 1,
    borderColor: '#fde68a',
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  noticeMutedText: {
    color: '#b45309',
    fontSize: 11,
    fontWeight: '700',
  },
  noticeInfo: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#f0f9ff',
    borderBottomWidth: 1,
    borderColor: '#bae6fd',
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  noticeInfoText: {
    color: '#0369a1',
    fontSize: 11,
    fontWeight: '700',
  },

  messagesList: {
    flex: 1,
    width: '100%',
    backgroundColor: '#f4f7f5',
  },
  messagesContent: {
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 12,
    minHeight: '100%',
  },
  dateDivider: {
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '700',
    marginVertical: 14,
    backgroundColor: '#f1f5f9',
    alignSelf: 'center',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
  },
  msgRow: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-end',
    marginBottom: 8,
  },
  msgRowMine: {
    flexDirection: 'row',
  },
  otherAvatar: {
    marginRight: 8,
  },
  otherAvatarImg: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  otherAvatarFallback: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  otherAvatarLetter: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
  },
  msgBubble: {
    maxWidth: Platform.OS === 'web' ? 560 : '82%',
    borderRadius: 18,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  msgBubbleMine: {
    backgroundColor: '#059669',
    borderBottomLeftRadius: 4,
    shadowColor: '#064e3b',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  msgBubbleOther: {
    backgroundColor: '#fff',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 1,
    borderBottomRightRadius: 4,
    borderWidth: 1,
    borderColor: '#dbe7e1',
  },
  msgText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#0f172a',
    textAlign: 'right',
  },
  msgTextMine: {
    color: '#fff',
  },
  msgMeta: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 3,
  },
  msgMetaMine: {
    justifyContent: 'flex-end',
  },
  msgTime: {
    fontSize: 10,
    color: '#94a3b8',
  },
  msgTimeMine: {
    color: 'rgba(255,255,255,0.7)',
  },

  emptyConv: {
    alignItems: 'center',
    paddingVertical: 50,
  },
  emptyConvIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#ecfdf5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptyConvAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  emptyConvAvatarFallback: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#ecfdf5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyConvAvatarLetter: {
    fontSize: 26,
    fontWeight: '900',
    color: '#059669',
  },
  emptyConvName: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0f172a',
    marginBottom: 4,
  },
  emptyConvBio: {
    fontSize: 13,
    color: '#64748b',
    textAlign: 'center',
    marginHorizontal: 32,
    marginBottom: 10,
  },
  emptyConvHint: {
    fontSize: 12,
    color: '#059669',
    fontWeight: '700',
  },

  composerWrap: {
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 3,
  },
  quickPromptsRow: {
    flexDirection: 'row-reverse',
    paddingHorizontal: 12,
    gap: 8,
    paddingBottom: 8,
  },
  quickPromptPill: {
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  quickPromptText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#065f46',
  },
  stickerPanel: {
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  stickerTitle: {
    textAlign: 'right',
    paddingHorizontal: 14,
    color: '#334155',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  stickerRow: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    gap: 5,
  },
  stickerItem: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stickerEmoji: {
    fontSize: 25,
  },
  messageImage: {
    width: 240,
    height: 220,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
  },
  imageCaption: {
    fontSize: 13,
    color: '#334155',
    textAlign: 'right',
    marginTop: 6,
    fontWeight: '700',
  },
  imageMsgContainer: {
    marginBottom: 2,
  },
  imagePressable: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  lightboxBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.94)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  lightboxCloseBtn: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 56 : 28,
    left: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  lightboxImage: {
    width: '100%',
    height: '80%',
  },
  locationCardOuter: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 12,
    minWidth: 220,
    maxWidth: 290,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 4,
  },
  locationCardOuterMine: {
    backgroundColor: '#ffffff',
    borderColor: '#a7f3d0',
  },
  locationCardHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  locationPinIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ecfdf5',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  locationPinIconWrapMine: {
    backgroundColor: '#ecfdf5',
  },
  locationInfoCol: {
    flex: 1,
    alignItems: 'flex-end',
  },
  locationHeaderTitle: {
    fontSize: 11,
    color: '#059669',
    fontWeight: '800',
    marginBottom: 2,
    textAlign: 'right',
  },
  locationDistrictTitle: {
    fontSize: 15,
    color: '#0f172a',
    fontWeight: '900',
    textAlign: 'right',
  },
  locationNavBtn: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#059669',
    borderRadius: 12,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  locationNavBtnText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
  },
  inputArea: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 4,
  },
  attachCircleBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachCircleBtnBusy: {
    backgroundColor: '#ecfdf5',
    borderColor: '#a7f3d0',
  },
  inputCapsule: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 22,
    paddingHorizontal: 10,
    minHeight: 44,
  },
  textInput: {
    flex: 1,
    fontSize: 14,
    color: '#0f172a',
    textAlign: 'right',
    maxHeight: 100,
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
  emojiInsideBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#059669',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#059669',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 3,
  },
  sendButtonDisabled: {
    backgroundColor: '#059669',
    opacity: 0.55,
  },
  blockedInputArea: {
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: '#fca5a5',
    padding: 16,
    alignItems: 'center',
    gap: 10,
  },
  blockedInputText: {
    color: '#dc2626',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  unblockActionBtn: {
    backgroundColor: '#dc2626',
    paddingHorizontal: 20,
    paddingVertical: 9,
    borderRadius: 12,
  },
  unblockActionBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },

  optionsOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  optionsSheet: {
    width: '92%',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  optionsHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderColor: '#f1f5f9',
    paddingBottom: 10,
  },
  optionsTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0f172a',
    flex: 1,
    textAlign: 'right',
  },
  optionsClose: {
    padding: 4,
  },
  optionRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: '#f8fafc',
  },
  optionRowText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#334155',
    textAlign: 'right',
  },
  optionRowSub: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 2,
    fontWeight: '600',
  },
  choiceCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#bae6fd',
    backgroundColor: '#f0f9ff',
  },
  choiceCardDanger: {
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
  },
  choiceTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0f172a',
    textAlign: 'right',
  },
  choiceSub: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 3,
    lineHeight: 16,
  },

  coffeeCircleBtn: {
    backgroundColor: '#fffbeb',
    borderColor: '#fde68a',
  },
  quickPromptPillCoffee: {
    backgroundColor: '#fffbeb',
    borderColor: '#fde68a',
  },
  quickPromptTextCoffee: {
    fontSize: 12,
    fontWeight: '800',
    color: '#92400e',
  },
  appreciationCardOuter: {
    borderRadius: 18,
    overflow: 'hidden',
    minWidth: 230,
    maxWidth: 320,
    borderWidth: 1.5,
    borderColor: '#fde68a',
    shadowColor: '#b45309',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
    marginBottom: 4,
  },
  appreciationCardOuterMine: {
    borderColor: '#fbbf24',
  },
  appreciationGrad: {
    padding: 13,
    borderRadius: 16,
  },
  appreciationTopRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  appreciationBadge: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#fde68a',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  appreciationBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#92400e',
  },
  appreciationCoffeeIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fde68a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appreciationTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#78350f',
    textAlign: 'right',
    marginBottom: 4,
  },
  appreciationNoteText: {
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '700',
    color: '#451a03',
    textAlign: 'right',
    marginBottom: 8,
  },
  appreciationDivider: {
    height: 1,
    backgroundColor: 'rgba(180, 83, 9, 0.15)',
    marginBottom: 6,
  },
  appreciationFooterRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 5,
  },
  appreciationFooterText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#92400e',
    textAlign: 'right',
  },

  /* Modal */
  appreciationModalCard: {
    width: '92%',
    maxWidth: 480,
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 16,
    elevation: 8,
  },
  appreciationModalHeader: {
    marginBottom: 12,
  },
  appreciationModalTitleCol: {
    alignItems: 'center',
    marginTop: 2,
  },
  appreciationModalIconCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#fef3c7',
    borderWidth: 2,
    borderColor: '#fde68a',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  appreciationModalTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#78350f',
    marginBottom: 4,
    textAlign: 'center',
  },
  appreciationModalSub: {
    fontSize: 12,
    lineHeight: 18,
    color: '#64748b',
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  appreciationSectionLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#334155',
    textAlign: 'right',
    marginBottom: 8,
  },
  appreciationChipsWrap: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  appreciationChip: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
  },
  appreciationChipSelected: {
    backgroundColor: '#fef3c7',
    borderColor: '#f59e0b',
  },
  appreciationChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  appreciationChipTextSelected: {
    color: '#92400e',
    fontWeight: '900',
  },
  appreciationInput: {
    backgroundColor: '#f8fafc',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 14,
    padding: 10,
    fontSize: 13,
    color: '#0f172a',
    textAlign: 'right',
    minHeight: 60,
    maxHeight: 100,
    marginBottom: 12,
  },
  appreciationActionRow: {
    marginTop: 2,
  },
  appreciationSendBtn: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#059669',
    paddingVertical: 12,
    borderRadius: 14,
    shadowColor: '#059669',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  appreciationSendBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
});
