import { StyleSheet, Platform } from 'react-native';

export const ADMIN_COLORS = {
  bg: '#F8FAFC',
  card: '#FFFFFF',
  ink: '#0F172A',
  inkMuted: '#475569',
  muted: '#64748B',
  subtle: '#94A3B8',
  border: '#E2E8F0',
  borderLight: '#F1F5F9',
  
  // Executive Emerald & Saudi Green
  accent: '#059669',
  accentLight: '#ECFDF5',
  accentDark: '#047857',
  
  // Luxury Dark Mode Navy
  navyDark: '#090D16',
  navyMid: '#0F172A',
  navyLight: '#1E293B',
  
  // State colors
  danger: '#EF4444',
  dangerLight: '#FEE2E2',
  success: '#10B981',
  successLight: '#D1FAE5',
  warning: '#F59E0B',
  warningLight: '#FEF3C7',
  info: '#0284C7',
  infoLight: '#E0F2FE',
  purple: '#7C3AED',
  purpleLight: '#F5F3FF',
};

export const adminStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ADMIN_COLORS.bg,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: ADMIN_COLORS.bg,
  },
  loadingText: {
    marginTop: 14,
    fontSize: 14,
    color: ADMIN_COLORS.muted,
    fontWeight: '600',
  },

  // Unauthorized state
  unauthorizedIconWrap: {
    width: 88,
    height: 88,
    borderRadius: 44,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
  },
  unauthorizedTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: ADMIN_COLORS.ink,
    textAlign: 'center',
    marginBottom: 8,
  },
  unauthorizedSub: {
    fontSize: 13,
    color: ADMIN_COLORS.muted,
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 420,
    marginBottom: 24,
  },
  backBtn: {
    backgroundColor: ADMIN_COLORS.navyMid,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 14,
  },
  backBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },

  // Toast feedback banner
  toastBanner: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 56 : 24,
    left: 20,
    right: 20,
    zIndex: 9999,
    backgroundColor: '#0F172A',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
    alignItems: 'center',
  },
  toastBannerText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },

  // 1. Executive Dark Command Header
  headerGrad: {
    paddingTop: Platform.OS === 'ios' ? 52 : 36,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 10,
  },
  headerContent: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  headerTexts: {
    flex: 1,
    marginHorizontal: 12,
    alignItems: 'flex-end',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  headerSub: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 2,
    fontWeight: '600',
  },
  headerActionBtn: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },

  // Operational status ribbons
  alertsRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  alertPill: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
  },
  alertPillText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },

  // 2. Navigation Tab Bar
  tabBarWrapper: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  tabBarScroll: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row-reverse',
    gap: 8,
  },
  navTabPill: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 22,
    backgroundColor: '#F1F5F9',
  },
  navTabPillActive: {
    backgroundColor: ADMIN_COLORS.navyMid,
  },
  navTabPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  navTabPillTextActive: {
    color: '#FFFFFF',
  },
  navTabBadge: {
    backgroundColor: ADMIN_COLORS.danger,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    marginLeft: 2,
  },
  navTabBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },

  // Scroll Container
  scroll: {
    flex: 1,
  },
  section: {
    padding: 16,
  },
  sectionHeaderRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
  },
  sectionSubDesc: {
    fontSize: 12,
    color: ADMIN_COLORS.muted,
    lineHeight: 18,
    textAlign: 'right',
    marginBottom: 16,
  },
  countBadge: {
    backgroundColor: ADMIN_COLORS.infoLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
  },
  countBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: ADMIN_COLORS.info,
  },

  // KPI Statistics Cards
  statsGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 18,
  },
  statCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  statIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    marginBottom: 10,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '900',
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
  },
  statLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: ADMIN_COLORS.inkMuted,
    textAlign: 'right',
    marginTop: 2,
  },
  statSub: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
    textAlign: 'right',
    marginTop: 4,
  },

  // Saudi Cities Distribution Card
  citiesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
  },
  citiesCardHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  citiesCardTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
  },
  citiesCardSub: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
  },
  cityPillsRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
  },
  cityPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  cityPillActive: {
    backgroundColor: ADMIN_COLORS.accent,
    borderColor: ADMIN_COLORS.accent,
  },
  cityPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: ADMIN_COLORS.inkMuted,
  },
  cityPillTextActive: {
    color: '#FFFFFF',
  },

  // Health Card
  healthCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 18,
  },
  healthHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: 10,
  },
  healthStatusBadge: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  healthDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
  },
  healthStatusText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#10B981',
  },
  healthRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  healthLabel: {
    fontSize: 12,
    color: ADMIN_COLORS.muted,
  },
  healthValueActive: {
    fontSize: 12,
    fontWeight: '700',
    color: ADMIN_COLORS.ink,
  },
  healthValueRole: {
    fontSize: 12,
    fontWeight: '700',
    color: ADMIN_COLORS.accent,
  },

  // Shortcuts
  quickAction: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 10,
  },
  quickActionLeft: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  quickActionText: {
    fontSize: 13,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
  },
  qBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  qBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },

  // Search & Filter rows
  searchBar: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 12,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
    padding: 0,
  },
  filterRow: {
    flexDirection: 'row-reverse',
    gap: 8,
    marginBottom: 14,
  },
  filterPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  filterPillActive: {
    backgroundColor: ADMIN_COLORS.navyMid,
    borderColor: ADMIN_COLORS.navyMid,
  },
  filterPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  filterPillTextActive: {
    color: '#FFFFFF',
  },

  // User Cards
  userCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  userCardAdmin: {
    borderColor: '#FDE68A',
    backgroundColor: '#FFFDF5',
  },
  userCardBanned: {
    borderColor: '#FECACA',
    backgroundColor: '#FEF2F2',
  },
  userCardHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  userAvatarWrap: {
    position: 'relative',
    marginLeft: 12,
  },
  userAvatarImg: {
    width: 48,
    height: 48,
    borderRadius: 16,
  },
  userAvatarFallback: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: ADMIN_COLORS.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  userAvatarLetter: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  adminCrownBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#F59E0B',
    borderRadius: 8,
    padding: 2,
  },
  userMeta: {
    flex: 1,
    alignItems: 'flex-end',
  },
  userName: {
    fontSize: 14,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
  },
  userHandle: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
    marginTop: 2,
  },
  userLocation: {
    fontSize: 11,
    color: ADMIN_COLORS.inkMuted,
    marginTop: 2,
  },
  roleBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  roleBadgeAdmin: {
    backgroundColor: '#FEF3C7',
  },
  roleBadgeUser: {
    backgroundColor: '#F1F5F9',
  },
  roleBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  roleBadgeTextAdmin: {
    color: '#D97706',
  },
  roleBadgeTextUser: {
    color: '#64748B',
  },
  userActionsRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  userActionBtn: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  userActionBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: ADMIN_COLORS.inkMuted,
  },
  btnDemote: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FDE68A',
  },
  btnPromote: {
    backgroundColor: '#F0F9FF',
    borderColor: '#BAE6FD',
  },
  btnActiveSuccess: {
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
  },
  btnBan: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
  },
  btnBannedActive: {
    backgroundColor: '#DC2626',
    borderColor: '#DC2626',
  },

  // Verification Dossier Cards
  verifCardDossier: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 14,
  },
  dossierTop: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  dossierAvatarWrap: {
    position: 'relative',
    marginLeft: 12,
  },
  dossierAvatarImg: {
    width: 48,
    height: 48,
    borderRadius: 16,
  },
  dossierAvatarFallback: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: ADMIN_COLORS.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dossierAvatarLetter: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  verifiedCheckBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: '#0284C7',
    borderRadius: 8,
    padding: 2,
  },
  dossierUserMeta: {
    flex: 1,
    alignItems: 'flex-end',
  },
  dossierUserName: {
    fontSize: 14,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
  },
  dossierHandle: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
    marginTop: 2,
  },
  dossierLocation: {
    fontSize: 11,
    color: ADMIN_COLORS.inkMuted,
    marginTop: 2,
  },
  verifStatusPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  verifPending: {
    backgroundColor: '#FEF3C7',
  },
  verifApproved: {
    backgroundColor: '#D1FAE5',
  },
  verifRejected: {
    backgroundColor: '#FEE2E2',
  },
  verifPendingText: {
    color: '#D97706',
    fontSize: 11,
    fontWeight: '800',
  },
  verifApprovedText: {
    color: '#059669',
    fontSize: 11,
    fontWeight: '800',
  },
  verifRejectedText: {
    color: '#DC2626',
    fontSize: 11,
    fontWeight: '800',
  },
  dossierNoteBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  dossierNoteTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
  },
  dossierNoteText: {
    fontSize: 12,
    color: ADMIN_COLORS.inkMuted,
    textAlign: 'right',
    marginTop: 4,
    lineHeight: 18,
  },
  dossierFootprintRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 10,
    marginTop: 12,
  },
  footprintItem: {
    alignItems: 'center',
  },
  footprintLabel: {
    fontSize: 10,
    color: ADMIN_COLORS.muted,
  },
  footprintVal: {
    fontSize: 12,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
    marginTop: 2,
  },
  dossierActionsRow: {
    flexDirection: 'row-reverse',
    gap: 8,
    marginTop: 14,
  },
  btnApproveVerif: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: ADMIN_COLORS.accent,
    paddingVertical: 9,
    borderRadius: 12,
  },
  btnApproveVerifText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  btnRejectVerif: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: '#FEE2E2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnRejectVerifText: {
    color: '#DC2626',
    fontSize: 12,
    fontWeight: '800',
  },
  btnInspectCitizen: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#E0F2FE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dossierCompletedFooter: {
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  dossierCompletedText: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
    textAlign: 'right',
  },

  // Reports
  reportCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 14,
  },
  reportHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  reportStatusTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  repPendingTag: {
    backgroundColor: '#FEE2E2',
  },
  repDoneTag: {
    backgroundColor: '#D1FAE5',
  },
  reportStatusText: {
    fontSize: 11,
    fontWeight: '800',
  },
  repPendingText: {
    color: '#DC2626',
  },
  repDoneText: {
    color: '#059669',
  },
  reportType: {
    fontSize: 13,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
  },
  reportReason: {
    fontSize: 13,
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
    fontWeight: '600',
    marginBottom: 8,
  },
  reportMetaRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  reportDate: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
  },
  reportFrom: {
    fontSize: 11,
    color: ADMIN_COLORS.inkMuted,
    fontWeight: '600',
  },
  reportActionsGrid: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  btnDeleteContent: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#DC2626',
    paddingVertical: 9,
    borderRadius: 12,
  },
  btnActionTextWhite: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  resolveBtn: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#10B981',
    paddingVertical: 8,
    borderRadius: 12,
  },
  resolveBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  dismissBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dismissBtnText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '800',
  },

  // Platform items (Services, Borrow Items, Urgent Alerts)
  platformItemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 10,
  },
  platformItemTop: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  platformItemTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
    flex: 1,
    marginLeft: 8,
  },
  platformItemSub: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
    textAlign: 'right',
    marginTop: 3,
  },
  platformItemActions: {
    flexDirection: 'row-reverse',
    gap: 8,
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  smallActionBtn: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  smallActionText: {
    fontSize: 11,
    fontWeight: '700',
    color: ADMIN_COLORS.inkMuted,
  },
  subSectionTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
    marginTop: 16,
    marginBottom: 10,
  },

  // Community Content (Questions & Requests)
  contentItemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 10,
  },
  contentItemHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  contentAuthorName: {
    fontSize: 12,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
  },
  contentItemCity: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
  },
  contentItemTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
  },
  contentItemBody: {
    fontSize: 12,
    color: ADMIN_COLORS.muted,
    textAlign: 'right',
    marginTop: 4,
    lineHeight: 18,
  },
  contentItemFooter: {
    flexDirection: 'row-reverse',
    justifyContent: 'flex-start',
    gap: 8,
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  btnDeleteSm: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: '#FEE2E2',
  },
  btnDeleteSmText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#DC2626',
  },
  btnViewSm: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: '#E0F2FE',
  },
  btnViewSmText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0284C7',
  },

  // Broadcast Box
  broadcastBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginTop: 8,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
    marginBottom: 6,
  },
  formInput: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
    fontSize: 13,
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
  },
  templatePillsRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  templatePill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
  },
  templatePillText: {
    fontSize: 11,
    fontWeight: '700',
    color: ADMIN_COLORS.ink,
  },
  previewBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    padding: 12,
    marginTop: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  previewHeading: {
    fontSize: 11,
    fontWeight: '800',
    color: ADMIN_COLORS.muted,
    textAlign: 'right',
    marginBottom: 8,
  },
  previewNotificationCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  previewCardHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  previewAppName: {
    fontSize: 10,
    fontWeight: '800',
    color: ADMIN_COLORS.muted,
  },
  previewTitleText: {
    fontSize: 13,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
  },
  previewBodyText: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
    textAlign: 'right',
    marginTop: 2,
    lineHeight: 16,
  },
  btnSendBroadcast: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: ADMIN_COLORS.accent,
    paddingVertical: 12,
    borderRadius: 14,
    marginTop: 16,
  },
  btnSendBroadcastText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },

  // Audit Logs
  auditLogCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 8,
  },
  auditLogIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#E0F2FE',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  auditLogMeta: {
    flex: 1,
    alignItems: 'flex-end',
  },
  auditLogAction: {
    fontSize: 12,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
  },
  auditLogTarget: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
    marginTop: 2,
  },
  auditLogTime: {
    fontSize: 10,
    color: ADMIN_COLORS.subtle,
    fontWeight: '600',
  },

  // User Dossier Inspector Modal
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15,23,42,0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10000,
    padding: 16,
  },
  modalDossierBox: {
    width: '100%',
    maxWidth: 540,
    maxHeight: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 12,
  },
  modalDossierHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalDossierTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: ADMIN_COLORS.ink,
  },
  modalDossierScroll: {
    marginTop: 12,
  },
  modalProfileCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 14,
    borderRadius: 16,
  },
  modalAvatarWrap: {
    position: 'relative',
    marginLeft: 12,
  },
  modalAvatarImg: {
    width: 54,
    height: 54,
    borderRadius: 18,
  },
  modalAvatarFallback: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: ADMIN_COLORS.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalAvatarLetter: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  modalAdminBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#F59E0B',
    borderRadius: 8,
    padding: 2,
  },
  modalUserInfo: {
    flex: 1,
    alignItems: 'flex-end',
  },
  modalName: {
    fontSize: 15,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
  },
  modalHandle: {
    fontSize: 12,
    color: ADMIN_COLORS.muted,
    marginTop: 2,
  },
  modalCity: {
    fontSize: 11,
    color: ADMIN_COLORS.inkMuted,
    marginTop: 2,
  },
  modalFootprintRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-around',
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    padding: 12,
    marginTop: 12,
  },
  modalFootprintBox: {
    alignItems: 'center',
  },
  modalFootprintNum: {
    fontSize: 16,
    fontWeight: '900',
    color: ADMIN_COLORS.ink,
  },
  modalFootprintLabel: {
    fontSize: 11,
    color: ADMIN_COLORS.muted,
    marginTop: 2,
  },
  modalSectionLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
    marginTop: 16,
    marginBottom: 8,
  },
  modalActionItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 8,
  },
  modalActionTitle: {
    fontSize: 12,
    fontWeight: '800',
  },
  modalActionSub: {
    fontSize: 10,
    color: ADMIN_COLORS.muted,
    marginTop: 2,
  },
  itemDemote: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FDE68A',
  },
  itemPromote: {
    backgroundColor: '#F0F9FF',
    borderColor: '#BAE6FD',
  },
  itemSuccess: {
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
  },
  itemBan: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
  },
  itemBanned: {
    backgroundColor: '#DC2626',
    borderColor: '#DC2626',
  },
  modalDirectMsgInput: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
    fontSize: 12,
    color: ADMIN_COLORS.ink,
    textAlign: 'right',
    height: 70,
    textAlignVertical: 'top',
  },
  btnSendNotice: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: ADMIN_COLORS.navyMid,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 10,
  },
  btnSendNoticeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },

  // Empty state
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: ADMIN_COLORS.ink,
    marginTop: 12,
  },
  emptySub: {
    fontSize: 12,
    color: ADMIN_COLORS.muted,
    textAlign: 'center',
    marginTop: 4,
  },
  trashActionBtn: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#FEE2E2',
  },
});
